### ISSUE TITLE
error when starting bot.js

### ISSUE THREAD

**Issue by b0rgie** [ngittlen/TwitchAutoGifBot#8]
[error screen shot](https://gyazo.com/a8286d6ddd346926e12fc2dbd5ba34f5)

i have done a number of trouble shooting steps as far as, making sure node was installed, java was installed, registered vbscript.dll jscript.dll not sure what i'm missing. i know this an old project, just trying to help out a friend. any info would be a great help. thank you for your time.

**Comment by ngittlen** [comment]
Did you run the command `node bot.js` to start it? This looks like you just double-clicked on the js file which isn't the same as running it with node

**Comment by b0rgie** [comment]
so i just did that.  and got this error. [new error](https://gyazo.com/48c9cd937e09856c061464a59086779a) figured it out! ty for the bread crumb!
